### ISSUE TITLE
Powershell modules not installed for nonroot user

### ISSUE THREAD

**Issue by Gozdew** [kichristensen/pwsh-mixin#9]
The nonroot user, which porter executes the invocation image as, does not get the modules installed (can't do Import-Module). They are installed for the root user. If the modules are installed using the `-Scope AllUsers` they are available.

Related code (output to Dockerfile):
https://github.com/kichristensen/pwsh-mixin/blob/54dbf7ee55ad7fca8e631bc8415b5c239f0e03fb/pkg/pwsh/build.go#L66
https://github.com/kichristensen/pwsh-mixin/blob/54dbf7ee55ad7fca8e631bc8415b5c239f0e03fb/pkg/pwsh/build.go#L68

(Also update related tests' expected outputs.)

**Comment by kichristensen** [comment]
@Gozdew thanks for reporting this. Would you be willing to make a PR with the changes?

**Comment by Gozdew** [comment]
Attempting my first github pull request :)

**Comment by kichristensen** [comment]
@Gozdew It looked good to me, and it have been merged. I will cut a new release tomorrow

**Comment by Gozdew** [comment]
Thank you :)
